name: Testing
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  log_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "18.x"
      - name: Bootstrap
        run: |
          npm ci
          npx lerna bootstrap
          npx lerna run build
          npx lerna run test
      - name: Log FOO_BAR
        run: echo $FOO_BAR
        env:
          FOO_BAR: ${{ secrets.FOO_BAR }}
